pwd
read -p "Are you sure to overwrite the makefile ?" -n 1 -r
echo   
if [[ $REPLY =~ ^[Yy]$ ]]
then
	rm -f Makefile
	srcs=$(find . -type f | grep ".\.c$" | xargs echo | tr " " "\n " | sed 's/\.c/\.c \\/g' | sed '$s/\\//')

	echo "# **************************************************************************** #" > Makefile
	echo "#                                                                              #" >> Makefile
	echo "#                                                         :::      ::::::::    #" >> Makefile
	echo "#    Makefile                                           :+:      :+:    :+:    #" >> Makefile
	echo "#                                                     +:+ +:+         +:+      #" >> Makefile
	echo "#    By: tcanaud <marvin@42.fr>                     +#+  +:+       +#+         #" >> Makefile
	echo "#                                                 +#+#+#+#+#+   +#+            #" >> Makefile
	echo "#    Created: 2017/05/03 19:01:11 by tcanaud           #+#    #+#              #" >> Makefile
	echo "#    Updated: 2017/05/05 17:10:57 by tcanaud          ###   ########.fr        #" >> Makefile
	echo "#                                                                              #" >> Makefile
	echo "# **************************************************************************** #" >> Makefile




	echo "BLACKBLACK=\\x1b[30m\\x1b[40m" >> Makefile
	echo "RED=\\x1b[31m" >> Makefile
	echo "GREEN=\\x1b[32m" >> Makefile
	echo "YELLOW=\\x1b[33m" >> Makefile
	echo "BLUE=\\x1b[34m" >> Makefile
	echo "PURPLE=\\x1b[35m" >> Makefile
	echo "CYAN=\\x1b[36m" >> Makefile
	echo "WHITE=\\x1b[37m" >> Makefile
	echo "BLACKGREEN=\\x1b[40m\\x1b[32m" >> Makefile
	echo "NOCOLOR=\\x1b[m" >> Makefile
	echo "ICONE=\\" >> Makefile
	echo "\$(BLACKGREEN) \$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN\$(BLACKGREEN)KN\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN\$(BLACKGREEN)KN\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)N\$(BLACKGREEN)KN\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)NKN\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)Xxo0\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)XxlcO\$(BLACKBLACK)WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WXX\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WKkxocO\$(BLACKBLACK)WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)W0d0\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)W0dkOll0\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)W0olOWWW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMM\$(BLACKGREEN)NkoxOxcx\$(BLACKBLACK)NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)KoclxKXKN\$(BLACKBLACK)MMMMMMMMMMMMMMMM\$(BLACKGREEN)Nklodo:c0\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMWWM\$(BLACKGREEN)Xo:odk0KXW\$(BLACKBLACK)MMMMMMMMMMMM\$(BLACKGREEN)WKOdoxkxl:xW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)NXNWXd;ckKKKXWWNX0KW\$(BLACKBLACK)MMMM\$(BLACKGREEN)N0dodkOd:;oX\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WNXXWWNxlxKKOO00OkxON\$(BLACKBLACK)MM\$(BLACKGREEN)WKdldxxkdc;oX\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)NXKKKNNN00X0ddxkOOxxXWXkllddddl;;dX\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)W0OKK0000K0xc:lxkxllkOolloolc:;:kW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\n\\" >> Makefile
	echo "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)NKOO0K00ODCCCLODOLCCLODOOLC:;:KW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WNKKKOKOLODDDDDDDDOODKKDL;,;XW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WWNOL:LOODXXXXXDDDOCCCCC:;,':0\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)W0XDDL;,;CLDDXXXDDOLC::CLLC;,CDOW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)0:,,''',:CLOOOOOOLC;;CLLLLC::OKK\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)KC,:;;,;:CCLLLLLC:LDOLLLLLCC:;;LK\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WOC:CLLCC::CCCC;,:ONXKOCLODXXOLCDN\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)NX;;:CCC:;;:C;. .'LKNKODXXXOLC::KW\$(BLACKBLACK)MMMMMMMMMMMMM\$(BLACKGREEN)WWWWWNNNNNNNNNNXXXXXK000OOKKKOXW\$(BLACKBLACK)M\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMM\$(BLACKGREEN)WWWW\$(BLACKBLACK)MM\$(BLACKGREEN)NX;,,...';::X0L. ...COKXDOC:;;,,'LX\$(BLACKBLACK)MMMMMMMM\$(BLACKGREEN)WWNNXKK0OKXDOOLCCCC::;;:COXO00KKKXN\$(BLACKBLACK)WMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMM\$(BLACKGREEN)WNX0KXDDDKOK\$(BLACKBLACK)X\$(BLACKGREEN)NK;''....;:CKKX,...':DDOC;,,,,,''DN\$(BLACKBLACK)MMMMMMM\$(BLACKGREEN)WX0OKDLC:;'..........':DOXW\$(BLACKBLACK)MMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)M\$(BLACKGREEN)X0OOKDOC;,......,CODOKD,'''';:LODKXOLLODDOL:;,'''..'LX\$(BLACKBLACK)MMMMMMM\$(BLACKGREEN)WODOL;'...'..........:ON\$(BLACKBLACK)MMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)M\$(BLACKGREEN)XOOOXO:,..........,:CODCCLLLLODDDDDDDOLC:;,,,,'..,:DX\$(BLACKBLACK)MMMMMMMM\$(BLACKGREEN)KO:;''..............CK\$(BLACKBLACK)MMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMM\$(BLACKGREEN)WXOO;........,;,;::CCLLOOLLLCC::;,,,,;,'..;KX\$(BLACKBLACK)NMMMMMMMM\$(BLACKGREEN)WK:;'...............,KW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMM\$(BLACKGREEN)XX,......',,',;;::CCCCCC::;;;;;:;,'.,LKW\$(BLACKBLACK)MMMMMMMMMM\$(BLACKGREEN)XD;,'............,CDON\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMM\$(BLACKGREEN)ND'.....'',,',;;:::::;;,,,,;;;,'.,O0W\$(BLACKBLACK)MMMMMMMMMMM\$(BLACKGREEN)W0C;,..........'CKXW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMM\$(BLACKGREEN)0C'......',,,;:\$(BLACKBLACK)LLDD\$(BLACKGREEN)OC,'',,''''':OW\$(BLACKBLACK)MMMMMMMMMMMM\$(BLACKGREEN)WXD:;'.........:OW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMW\$(BLACKGREEN)N0D:.....';;:\$(BLACKBLACK)XXNWMW0C\$(BLACKGREEN);;:;,,,'C0W\$(BLACKBLACK)MMMMMMMMMMM\$(BLACKGREEN)WXKODC,.........CK\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMM\$(BLACKGREEN)WXX,....';;\$(BLACKBLACK)CDKWMNX\$(BLACKGREEN):CC:;,,';OW\$(BLACKBLACK)MMMMMMMM\$(BLACKGREEN)WNK0OKKXL;.........;0\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WO;.....,;;:\$(BLACKBLACK)OKXC\$(BLACKGREEN):CC:;,,';KW\$(BLACKBLACK)MW\$(BLACKGREEN)NXXXK0OKKXDOC::::CCLLLOOOOW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WO;......',,,;:LOOC:;;,,CO0DLLODDDDOOOXKOKXNWWW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WK;,;:CCCC:,;CLOOLC::::;;;;;:CCC:;:O0W\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WXXNWWWWNK::CLODDOCCCLLLC::;,'''',;DXW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)XO;:CLODDOLCCLODOLC:,'..''';CKN\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)O:;:CLOODDOLLODDDOLC;'''',,,,;OK\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)NO,,::CCCLLCCLOODDOL:;''',;::;,,LK\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WK;',,,;::::::CLOOOOLC,''';CCC:;,,C0W\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)KC,;;,,,;;;::;;:LLOOLC;'',:LLCC:;,'C0\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)O;,;:;,,,;;::;;;CLLLLC:'.,:LLCC::;,,DN\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WK,,;:;;,',,,;;;,:CLLLC:'.';CCCCC::;,;XXN\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WK,,;:;;;,;:;',,',:LLLL:'..,:CCCC::;,'';LD0NW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)O;,;:;;;,\$(BLACKBLACK)OKD\$(BLACKGREEN),'''',:CLL;'...,CCC:::;,....';:XN\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)KL,;;:;;\$(BLACKBLACK)LKW0\$(BLACKGREEN):''''',:CC:;;:CLLC;;;;,'........C0W\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WX;;:::\$(BLACKBLACK)DX\$(BLACKBLACK)MMWO\$(BLACKGREEN):''''':LLCOOKWWWKO;,,,'.,:CC:,..;ONW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WKCCCCDX\$(BLACKBLACK)MMMMWKO\$(BLACKGREEN),''':ODLXKN\$(BLACKBLACK)MMMM\$(BLACKGREEN)NK;''''LK\$(BLACKBLACK)WWWX\$(BLACKGREEN)OO,';L0W\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)NXLOLXX\$(BLACKBLACK)MMMMMMMW0L\$(BLACKGREEN),':DDOONW\$(BLACKBLACK)MMMMM\$(BLACKGREEN)WKO,..;O\$(BLACKBLACK)MMMMM\$(BLACKGREEN)NL...CX\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WWNXK0KOOODK\$(BLACKBLACK)MMMMMWWNNX\$(BLACKGREEN)OL:ODOOOWW\$(BLACKBLACK)MMMMMMM\$(BLACKGREEN)WK:;:XN\$(BLACKBLACK)MMMMWK\$(BLACKGREEN)D:',K\$(BLACKBLACK)WMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)KXK0D:CLDO:XN\$(BLACKBLACK)MMWN0O0O\$(BLACKGREEN)OOKO:CLCD0KN\$(BLACKBLACK)MMMMM\$(BLACKGREEN)WXKOOOCLKXW\$(BLACKBLACK)MMMMMW\$(BLACKGREEN)X0K\$(BLACKBLACK)WMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)XOKXKDDDOKDK\$(BLACKBLACK)MMMWX0OO\$(BLACKGREEN)XLX0XOODX0NNW\$(BLACKBLACK)MMMMM\$(BLACKGREEN)WKXOOOLOOXW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)WWW\$(BLACKBLACK)M\$(BLACKGREEN)WWWW\$(BLACKBLACK)MMMMMMWWWW\$(BLACKGREEN)NNWWWW\$(BLACKBLACK)MMMMMMMMMMMMMMWWNNW\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(BLACKGREEN)\\\N\\" >> MAKEFILE
	ECHO "\$(BLACKBLACK)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\$(NOCOLOR)\\\N" >> MAKEFILE








	ECHO >> MAKEFILE
	ECHO "NAME = $1" >> MAKEFILE
	ECHO >> MAKEFILE
	ECHO "SOURCES = $SRCS" >> MAKEFILE
	ECHO >> MAKEFILE

	ECHO "OBJECTS = \$(SOURCES:.C=.O)" >> MAKEFILE
	ECHO "\$(NAME): \$(OBJECTS)" >> MAKEFILE
	ECHO "	@AR RC \$(NAME) \$(OBJECTS)" >> MAKEFILE
	ECHO "	@RANLIB \$(NAME)" >> MAKEFILE
	ECHO "	@PRINTF \"\\\R                                                                                                                                                             		\r\$(GREEN)\\\r\$(NAME) was created successfully !\$(NOCOLOR)\\\n\"" >> Makefile
	echo "" >> Makefile
	echo "echo:" >> Makefile
	echo "	@printf \"\$(ICONE)\\\n\"" >> Makefile
	echo "	@printf \"\$(PURPLE)Make the \$(NAME)\$(NOCOLOR)\\\n\"" >> Makefile
	echo "" >> Makefile
	echo "all: \$(NAME)" >> Makefile
	echo "" >> Makefile

	echo "%.o: %.c" >> Makefile
	echo "	@gcc -c -Wall -Wextra -Werror -o \$@ $< -I include/" >> Makefile
	echo "	@printf \"\\\r\$(PURPLE)\$@ $<\$(NOCOLOR)                                                                                                                                                         \\\r\"" >> Makefile
	echo "" >> Makefile
	echo "clean:" >> Makefile
	echo "	@printf \"\$(YELLOW)Remove the objects\$(NOCOLOR)\\\n\"" >> Makefile
	echo "	@rm -f \$(OBJECTS)" >> Makefile
	echo "" >> Makefile
	echo "fclean: clean" >> Makefile
	echo "	@printf \"\$(YELLOW)Remove \$(NAME)\$(NOCOLOR)\\\n\"" >> Makefile
	echo "	@rm -f \$(NAME)" >> Makefile
	echo "" >> Makefile
	echo "re: fclean all" >> Makefile
fi
